version: '3.8'

services:
  torrentflow:
    build: .
    image: torrentflow:latest
    container_name: torrentflow-app
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=your_secret_key_here
      - DATABASE_URL=sqlite:////app/db/torrentflow.db
      - TZ=Europe/Paris
    volumes:
      - ./data:/app/data
      - ./db:/app/db
    networks:
      - torrentflow-net

  redis:
    image: redis:7-alpine
    container_name: torrentflow-redis
    restart: unless-stopped
    networks:
      - torrentflow-net

networks:
  torrentflow-net:
    driver: bridge